name: Build NGINX (OpenSSL)

on:
  workflow_dispatch:
    inputs:
      nginx_version:
        description: 'Nginx version tag (e.g., release-1.29.1). Leave empty for latest stable.'
        required: false
      openssl_version:
        description: 'OpenSSL version tag (e.g., openssl-3.5.2). Leave empty for latest stable.'
        required: false

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libpcre2-8-0 libpcre2-dev zlib1g zlib1g-dev libssl-dev git sudo curl

      - name: Download NGINX source
        run: |
          cd ..
          git clone --no-checkout https://github.com/nginx/nginx.git
          cd nginx
          
          if [[ -n "${{ github.event.inputs.nginx_version }}" ]]; then
            NGINX_TAG=${{ github.event.inputs.nginx_version }}
          else
            NGINX_TAG=$(curl -s https://api.github.com/repos/nginx/nginx/git/refs/tags | \
              grep '"ref": "refs/tags/release-' | \
              grep -vE 'rc|beta|alpha' | \
              sed 's/.*refs\/tags\/\(release-[0-9.]*\).*/\1/' | \
              sort -V | tail -n 1)
          fi
          echo "Using NGINX version: $NGINX_TAG"
          
          git fetch --depth=1 origin refs/tags/$NGINX_TAG:refs/tags/$NGINX_TAG
          git checkout tags/$NGINX_TAG

      - name: Download OpenSSL source
        run: |
          cd ..
          git clone --no-checkout https://github.com/openssl/openssl.git
          cd openssl
          
          if [[ -n "${{ github.event.inputs.openssl_version }}" ]]; then
            OPENSSL_TAG=${{ github.event.inputs.openssl_version }}
          else
            OPENSSL_TAG=$(curl -s https://api.github.com/repos/openssl/openssl/git/refs/tags | \
              grep '"ref": "refs/tags/openssl-' | \
              grep -vE 'rc|beta|alpha' | \
              sed 's/.*refs\/tags\/\(openssl-[0-9.]*\).*/\1/' | \
              sort -V | tail -n 1)
          fi
          echo "Using OpenSSL version: $OPENSSL_TAG"
          
          git fetch --depth=1 origin refs/tags/$OPENSSL_TAG:refs/tags/$OPENSSL_TAG
          git checkout tags/$OPENSSL_TAG

      - name: Build Nginx
        run: |
          cd ../nginx
          ./auto/configure --prefix=/usr/local/nginx --with-compat --with-http_v2_module \
            --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module \
            --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module \
            --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module \
            --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module \
            --with-http_v3_module --with-stream --with-stream_realip_module --with-stream_ssl_module \
            --with-stream_ssl_preread_module \
            --with-openssl=../openssl \
            --with-openssl-opt="enable-ktls"
          make -j$(nproc)
          sudo make install

      - name: Verify Nginx version
        run: /usr/local/nginx/sbin/nginx -V

      - name: Package Nginx binary
        run: |
          cd /usr/local/nginx
          sudo tar -czvf nginx-built.tar.gz sbin/ conf/ html/ logs/
          sudo mv nginx-built.tar.gz $GITHUB_WORKSPACE

      - name: Set TAG_NAME with UTC date
        run: echo "DATE=v$(date -u +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "BUILD ${{ env.DATE }}"
          path: nginx-built.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: "BUILD_${{ env.DATE }}"
          draft: false
          prerelease: false
          files: nginx-built.tar.gz
